<?php

use Drupal\image\Entity\ImageStyle;

/**
 * @file
 * Provides an Panorama Effect field formatter for Image fields.
 *
 * This module provides a field formatter that allows users to specify an image
 * style to display, and another image style to use as the panorama effect version of the
 * image.
 */

/**
 * Implements hook_theme().
 */
function pannellum_theme($existing, $type, $theme, $path)
{
  return [
    'panorama_effect' => [
      'variables' => [
        'item' => NULL,
        'display_style' => NULL,
        'settings' => NULL,
        'pannellum_autoload' => NULL,
      ],
      'template' => 'panorama-effect',
    ],
  ];
}

/**
 * Preprocess function for panorama_effect.
 */
function template_preprocess_panorama_effect(&$variables)
{
  static $index = 0;
  $item = $variables['item'];

  if ($variables['display_style']) {

    $variables['image'] = ImageStyle::load($variables['display_style'])->buildUrl($item->entity->getFileUri());
    $image = Drupal::service('image.factory')->get($variables['image']);
    $info['width'] = $image->getWidth();
    $info['height'] = $image->getHeight();
  } else {
    $variables['image'] = file_create_url($item->entity->getFileUri());
    $image = Drupal::service('image.factory')->get($variables['pannellum']);
    $info['width'] = $image->getWidth();
    $info['height'] = $image->getHeight();
  }

  $variables['effectType'] = $variables['settings']['type'];
  $variables['autoload'] = $variables['pannellum_autoload']?:0;
  $variables['width'] = $info['width'] . 'px';
  $variables['height'] = $info['height']. 'px';
  $variables['alt'] = $item->alt;
  $variables['id'] = $variables['settings']['id'] . $variables['item']->getValue()['target_id'];
  $variables['title'] = $item->title;

  //Attaching a image src and autoload variables with drupalsettings
  $variables['#attached']['drupalSettings']['pannellum'][$index]['id'] = $variables['id'];
  $variables['#attached']['drupalSettings']['pannellum'][$index]['src'] = $variables['image'];
  $variables['#attached']['drupalSettings']['pannellum'][$index]['autoload'] = $variables['autoload'];
  $index = $index+1;
}
